1 thread for windows and macos tests

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -74,28 +74,29 @@ jobs:
     - name: Run tests 
       timeout-minutes: 15
       run: |
-        $failed = $false
-        cargo test --doc maths;       if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc ui;          if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc framework;   if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc tools;       if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc sound;       if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc interactor;  if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc system;      if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc permission;  if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc material;    if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc shader;      if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc tex;         if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc sprite;      if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc font;        if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc render_list; if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc anchor;      if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc compute;     if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc util;        if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc sk;          if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc mesh;        if ($LASTEXITCODE -ne 0) { $failed = $true }
-        cargo test --doc model;       if ($LASTEXITCODE -ne 0) { $failed = $true }
-        if ($failed) { exit 1 }
+        cargo test -- --nocapture --test-threads=1
+        # $failed = $false
+        # cargo test --doc maths;       if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc ui;          if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc framework;   if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc tools;       if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc sound;       if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc interactor;  if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc system;      if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc permission;  if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc material;    if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc shader;      if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc tex;         if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc sprite;      if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc font;        if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc render_list; if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc anchor;      if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc compute;     if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc util;        if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc sk;          if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc mesh;        if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # cargo test --doc model;       if ($LASTEXITCODE -ne 0) { $failed = $true }
+        # if ($failed) { exit 1 }
 
     - name: Build no-event-loop
       run: cargo build --verbose --features no-event-loop --example manual
@@ -174,28 +175,29 @@ jobs:
       run: |
         export DYLD_LIBRARY_PATH=$(brew --prefix molten-vk)/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}
         export MVK_CONFIG_LOG_LEVEL=0
-        failed=0
-        timeout 3m cargo test --doc maths       -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc ui          -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc framework   -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc tools       -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc sound       -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc interactor  -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc system      -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc permission  -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc material    -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc shader      -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc tex         -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc sprite      -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc font        -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc render_list -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc anchor      -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc compute     -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc util        -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc sk          -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc mesh        -- --nocapture --test-threads=1 || failed=1
-        timeout 1m cargo test --doc model       -- --nocapture --test-threads=1 || failed=1
-        exit $failed
+        cargo test -- --nocapture --test-threads=1
+        # failed=0
+        # timeout 3m cargo test --doc maths       -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc ui          -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc framework   -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc tools       -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc sound       -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc interactor  -- --nocapture --test-threads=1 || failed=1
+        # timeout 3m cargo test --doc system      -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc permission  -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc material    -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc shader      -- --nocapture --test-threads=1 || failed=1
+        # timeout 2m cargo test --doc tex         -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc sprite      -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc font        -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc render_list -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc anchor      -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc compute     -- --nocapture --test-threads=1 || failed=1
+        # timeout 2m cargo test --doc util        -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc sk          -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc mesh        -- --nocapture --test-threads=1 || failed=1
+        # timeout 1m cargo test --doc model       -- --nocapture --test-threads=1 || failed=1
+        # exit $failed
 
     - name: Build no-event-loop
       run: cargo build --verbose --features no-event-loop --example manual
